title: "Pranav Unnikrishnan"
description: "Evolutionary biology • science communication • science art"
url: "https://upranav13.github.io"
baseurl: "/pk"                        
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: aqua

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM

author:
  name: "Pranav Unnikrishnan"
  avatar: "/assets/images/avatar.png"
  bio: "Evolutionary biologist | Designer & Artist"
  links:
    - label: "Email"
      url: "upranav13@gmail.com"
    - label: "ORCID"
      url: "https://orcid.org/my-orcid?orcid=0009-0003-8532-6324"
    - label: "GitHub"
      url: "https://github.com/upranav13"
